### ISSUE TITLE
Support login on Apple ID with security key

### ISSUE THREAD

**Issue by Toad882** [XcodesOrg/XcodesApp#357]
**Describe the bug**
When I try to login on an Apple ID that is configured with security key for 2 factor authentication, Xcodes shows error after I enter  email and password that stops me to sign in

**To Reproduce**
try to sign in with any Apple ID that use security key instead of 6 length code
**Expected behavior**
prompt to insert the security key and sign in successfully
**Screenshots**
![screen1](https://user-images.githubusercontent.com/44236086/219476809-a5ee2908-5353-48ce-9851-8c6c71203dc0.jpg)

**Version**
 - OS: 13.2.1
 - Xcodes: 1.9.0 (17)

**Comment by MattKiazyk** [comment]
Hi @Toad882 

Unfortunately we don't support security keys at this time. I'll change this ticket to an enhancement request. The error is indicating that the `securityCode` isn't returning back from `https://idmsa.apple.com/appleauth/auth` call, so obviously if an account is setup to use security keys this is wrong.

**Comment by feralbob** [comment]
I have the same issue. I tried creating an app specific password and that didn't work either. Gives the following error/message 
<img width="1188" alt="Screenshot 2023-02-16 at 9 55 41 PM" src="https://user-images.githubusercontent.com/8114/219529909-a7710b0a-5b85-4b68-b4da-09bc12e48257.png">

**Comment by shyuan** [comment]
I have the same issue.

I am wondering that if Apple provide some migration document to help developers use native Apple ID authentication flow.

![截圖 2023-02-13 上午10 18 57](https://user-images.githubusercontent.com/347809/219566682-594c7649-b3e2-4021-900e-4cfd63221af6.png)

**Comment by jaanus** [comment]
Just hit the same bug. This is unfortunate. I understand this is more on Apple's side than the Xcodes app.

**Comment by piersatdoshii** [comment]
Especially with the current push everywhere towards passkeys, I think this should be a high priority, thanks! 😄

**Comment by jaanus** [comment]
I have sort of given up on Xcodes supporting logging in with security key. It’s not their fault - it’s unclear if Apple ever intends logging in to their account with hardware security key to work with thirdparty things like Xcodes.

Xcodes is still very useful and I use it a lot. Just to see what versions I have installed, switch between them, see Swift versions etc, that is all great.

If it turns out that direct downloading is not possible with hardware security key, it would be very useful for Xcodes to automatically open the download location in my browser, where I can log in with the security key if needed, and just complete the download with my browser.
