### ISSUE TITLE
"Open In Rosetta" option greyed out on M1

### ISSUE THREAD

**Issue by lockieluke** [XcodesOrg/XcodesApp#421]
**Describe the bug**
"Open In Rosetta" option is greyed out on Apple Silicon

**To Reproduce**
- Open Settings
- Go to Advanced

**Expected behavior**
The option should be enabled for Apple Silicon-based machines

**Screenshots**
![image](https://github.com/XcodesOrg/XcodesApp/assets/25424409/9c2fc573-a046-4990-acd2-9eff4edc0f39)

**Version**
 - OS: Version 14.0 Beta (23A5337a)
 - Xcodes: 1.10.0 (18)

**Comment by MattKiazyk** [comment]
`Open in Rosetta` on Xcodes is going to removed in a future version. Since Xcode 14.3 it is no longer supported. 

https://developer.apple.com/documentation/xcode-release-notes/xcode-14_3-release-notes#Deprecations

For your issue, we only support it when using `Keep name as Xcode-x.x.x.app` option.
