### ISSUE TITLE
Changed code signature in version 2.0.2b23?

### ISSUE THREAD

**Issue by suschizu** [XcodesOrg/XcodesApp#490]
hello - I've noticed that the code signature has changed between (stable) version 1.10.0b18 and 2.0.2b23:

```
EXPECTED 'Robots and Pencils Inc. (PBH8V487HB)' 
FOUND 'Matt Kiazyk (ZU6GR6B2FY)'
```

can you confirm this @MattKiazyk? thanks!

**To Reproduce**
codesign -dv --verbose=4 /Path/To/Application.app

**Comment by MattKiazyk** [comment]
Hi @suschizu 

Correct. Because of the change in organizations (see [more info here]( https://github.com/XcodesOrg/XcodesApp/blob/main/nextstep.md)) it is now signed by my App Developer account. 

I would love to in the future have an actual XcodesOrg Developer Account, but doing that would take lots of time and money and I'm not sure yet if I want to go that route for a simple utility app.

Let me know if you have any more questions

**Comment by suschizu** [comment]
thanks for the fast answer - we wish you all the best here from corecode :)
