### ISSUE TITLE
App icon install progress bar stuck

### ISSUE THREAD

**Issue by jnozzi** [XcodesOrg/XcodesApp#529]
**Describe the bug**
After a successful installation, the app icon's progress bar remained at mostly-done. This is visible both in the dock and in the app switcher.

**To Reproduce**
I'm not exactly sure; I clicked to install 15.2, then clicked the iOS 17.2 installer shortly after, while the Xcode install was in progress. I haven't tried it again (I'm a bit swamped).

**Expected behavior**
When there're no running tasks, the app icon (both Dock and in app switcher) shouldn't show a progress bar.

**Screenshots**
I didn't think to take a screenshot. The progress bar had maybe <=10% left.

**Version**
 - OS: 14.4
 - Xcodes: 15.2, 15.3

**Comment by Kyle-Ye** [comment]
+1 for this issue.

This seems to be related with `resetDockProgressTracking` and `setupDockProgress` call.

cc @senmu 

I'll also debug this if I'm available this week.

**Comment by Kyle-Ye** [comment]
Found the issue here

<img width="1723" alt="image" src="https://github.com/XcodesOrg/XcodesApp/assets/43724855/536dc231-b28a-4fcc-8a61-5890d103e83b">

1. First we hit line 431 `unxipProgress.completedUnitCount = AppState.totalProgressUnits` and set progress to `0.9987682686384189`
2. Then we hit line 432 to call `resetDockProgressTracking()`

This should remove the overlay as the comments is saying. (At first, I suspect the bug is because we are missing `resetDockProgressTracking` call somewhere)
```swift
func resetDockProgressTracking() {
    DockProgress.progress = 1 // Only way to completely remove overlay with DockProgress is setting progress to complete
}
```

But it will actually do nothing in this case, because the previous progress is `0.9987682686384189` and the diff is less than `0.01` so the `DockProgress` just ignores the update.

```swift
// DockProgress.swift
public static var progress: Double = 0 {
	didSet {
		if previousProgress == 0 || (progress - previousProgress).magnitude > 0.01 {
			previousProgress = progress
			updateDockIcon()
		}
	}
}
```

We can fix it on our side or update the library version.

The latest upstream version has removed such limitation. https://github.com/sindresorhus/DockProgress/blob/fb80c50c8eac4c1143da6ec602b8fad760c1613a/Sources/DockProgress/DockProgress.swift#L107-L115

Also I was wondering why `DockProgress.resetProgress` is not working previously so that the original contributor is using `DockProgress.progress = 1` here.

Would you help to tell use what's the suggested way to reset/remove it? cc @sindresorhus

**Comment by Kyle-Ye** [comment]
XcodesApp is using DockProgress 3.2.0 now.

To solve the issue, I think upgrade the latest 4.3.0 would probably fix it.

And also we'd like to confirm the preferred way to reset the Dock bar: `DockProgress.progress = 1` or `DockProgress.resetProgress()`

**Comment by Kyle-Ye** [comment]
Update:

1. Update DockProgress 3.2.0 -> 4.3.0. XcodesApp will need some code change to adopt the new `@MainActor` check

2. Keep `DockProgress.progress = 1` or change it to `DockProgress.resetProgress()` will present a full progress bar and never disappear after the dependency update.

<img width="114" alt="image" src="https://github.com/XcodesOrg/XcodesApp/assets/43724855/4b12e4d7-c4e9-49eb-88e7-c5b67c8a06d6">

We may need to call other API to achieve the same effect(Present full progress bar and then disappear) after the update.

**Comment by Kyle-Ye** [comment]
This issue and #491 seems to be duplicated. Would you help close one as duplicated? @MattKiazyk

**Comment by Kyle-Ye** [comment]
This upstream has patched a commit to fix the issue.

Opened #545 and make it a draft due to a missing new release version from the upstream.

See detail here https://github.com/sindresorhus/DockProgress/issues/20#issuecomment-2028082964
